### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/wallets
Content-Type: application/json

{
  "fullName": "mateus madeira",
  "cpfCnpj": "37338190801",
  "email": "mafemad2005@gmail.com",
  "password": "Mafemad2005!",
  "walletType": "USER"
}
###
POST http://localhost:8080/wallets/4/deposit
Content-Type: application/json
Authorization: Bearer #token aqui

{
  "amount": 100
}

###
POST http://localhost:8080/transfer
Content-Type: application/json

{
  "value": 2,
  "payer": 1,
  "payee": 4
}

###
PUT http://localhost:8080/wallets/6
Content-Type: application/json

{
  "email": "mafemad203@gmail.com"
}

###
DELETE http://localhost:8080/wallets/


###
POST localhost:8080/auth/register
Content-Type: application/json

{
  "fullName": "mateus madeira",
  "cpfCnpj": "18563277871",
  "email": "mafemad2004@gmail.com",
  "password": "Mafemad2005!",
  "walletType": "USER"
}

###
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "mafemad2004@gmail.com",
  "password": "Mafemad2005!"
}