### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/wallets
Content-Type: application/json

{
  "fullName": "mateus madeira",
  "cpfCnpj": "123456789098",
  "email": "mafemad2005@gmail.com",
  "password": "1234",
  "walletType": "USER"
}