### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/wallets
Content-Type: application/json

{
  "fullName": "teste metodos",
  "cpfCnpj": "887.031.680-77",
  "email": "testando@email.com",
  "password": "Teste123!",
  "walletType": "USER"
}
###
POST http://localhost:8080/wallets/6/withdraw
Content-Type: application/json

{
  "amount": 100
}

###
POST http://localhost:8080/transfer
Content-Type: application/json

{
  "value": 2,
  "payer": 1,
  "payee": 4
}

###
PUT http://localhost:8080/wallets/6
Content-Type: application/json

{
  "email": "mafemad203@gmail.com"
}

###
DELETE http://localhost:8080/wallets/6
